name: MARS_SOM_CLEANER
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ‰ The Job was automatically triggered by a ${{ github.event_name }} Event."
    - run: echo "ğŸ§ This Job is now running on a ${{ runner.os }} Server hosted by GitHub!"
    - run: echo "ğŸ” The Name of Your Branch is ${{ github.ref }} and your Repository is ${{ github.repository }}."
    - uses: actions/checkout@v1
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='README.md' '.github/' --exclude='.gitignore' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
    - name: Bump Version and push Tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: Miustone }}
    - run: echo "ğŸ This Job's Status is ${{ job.status }}."